[workspace]
members = [
    "cooklang",
    "cli",
    "cooklang-fs",
    "cooklang-to-cooklang",
    "cooklang-to-human",
    "cooklang-to-md"
]

[profile.release]
# lto = true
# strip = true
# opt-level = "z"