[workspace]
members = [
    "cli",
    "cooklang-fs",
    "cooklang-to-cooklang",
    "cooklang-to-human",
    "cooklang-to-md"
]

[profile.release]
lto = "thin"
strip = true
# opt-level = "s"

# TODO remove in new ariadne release
[patch.crates-io]
ariadne = { git = "https://github.com/Zheoni/ariadne", branch = "update-concolor" }