default_units = true
warnings_as_errors = false
recipe_ref_check = true

[extensions]
MULTINE_STEPS = true
INGREDIENT_MODIFIERS = true
INGREDIENT_NOTE = true
INGREDIENT_ALIAS = true
SECTIONS = true
ADVANCED_UNITS = true
MODES = true
TEMPERATURE = true
TEXT_STEPS = true

[load]
