[si.prefixes]
kilo = ["kilo"]
hecto = ["hecto"]
deca = ["deca"]
deci = ["deci"]
centi = ["centi"]
milli = ["milli"]

[si.symbol_prefixes]
kilo = ["k"]
hecto = ["h"]
deca = ["da"]
deci = ["d"]
centi = ["c"]
milli = ["m"]

[[quantity]]
quantity = "volume"
best = { metric = ["ml", "l"], imperial = ["cup", "tsp", "tbsp"] }
[quantity.units]
metric = [
    { names = ["liter", "liters", "litre", "litres"], symbols = ["l", "L"], ratio = 1, expand_si = true },
]
imperial = [
    { names = ["cup", "cups"], symbols = ["c"], ratio = 0.2841306 },
    { names = ["tablespoon", "tablespoons"], symbols = ["tbs", "tbs.", "tbsp", "tbsp."], ratio = 0.01775816 },
    { names = ["teaspoon", "teaspoons"], symbols = ["tsp", "tsp."], ratio = 0.005919387 },
    { names = ["fluid ounce", "fluid ounces"], symbols = ["fl oz", "fl. oz.", "fl. oz", "fl oz."], ratio = 0.02841306 },
    { names = ["gallon", "gallons"], symbols = ["gal"], ratio = 4.54609 },
    { names = ["pint", "pints"], symbols = ["pt"], ratio = 0.5682612 },
    { names = ["quart", "quarts"], symbols = ["qt"], ratio = 1.136522 },
]

[[quantity]]
quantity = "length"
best = { metric = ["cm", "mm", "m"], imperial = ["in", "ft"] }
[quantity.units]
metric = [
    { names = ["meter", "meters", "metre", "metres"], symbols = ["m"], ratio = 1, expand_si = true },
]
imperial = [
    { names = ["foot", "feet"], symbols = ["ft", "'"], ratio = 0.3084 },
    { names = ["inch", "inches"], symbols = ["in", "\""], ratio = 0.0254 },
]

[[quantity]]
quantity = "mass"
best = { metric = ["mg", "g", "kg"], imperial = ["oz", "lb"] }
[quantity.units]
metric = [
    { names = ["gram", "grams"], symbols = ["g"], ratio = 1, expand_si = true },
]
imperial = [
    { names = ["ounce", "ounces"], symbols = ["oz", "oz."], ratio = 28.34952 },
    { names = ["pound", "pounds"], symbols = ["lb", "lb."], ratio = 453.5924 },
]

[[quantity]]
quantity = "time"
best = ["s", "h", "min", "d"]
units = [
    { names = ["second", "seconds"], symbols = ["s", "sec"], ratio = 1 },
    { names = ["minute", "minutes"], symbols = ["min"], ratio = 60 },
    { names = ["hour", "hours"], symbols = ["h"], ratio = 3600 },
    { names = ["day", "days"], symbols = ["d"], ratio = 86400 },
]

[[quantity]]
quantity = "temperature"
best = { metric = ["C"], imperial = ["F"] }
[quantity.units]
metric = [
    { names = ["celsius"], symbols = ["°C", "ºC", "℃", "C"], ratio = 1, difference = 273.15 },
]
imperial = [
    { names = ["fahrenheit"], symbols = ["°F", "ºF", "℉", "F"], ratio = 0.55555555556, difference = 459.67 }
]