[si.prefixes]
kilo = []
hecto = []
deca = []
deci = []
centi = []
milli = ["mili"]

[extend.names]
l = ["litro", "litros"]
c = ["taza", "tazas"]
"fl oz" = ["onza líquida", "onzas líquidas"]
gal = ["galón", "galones"]
pint = ["pinta", "pintas"]
quart = ["cuarto", "cuartos"]
m = ["metro", "metros"]
foot = ["pie", "pies"]
inch = ["pulgada", "pulgadas"]
gram = ["gramo", "gramos"]
ounce = ["onza", "onzas"]
pound = ["libra", "libras"]
s = ["segundo", "segundos"]
min = ["minuto", "minutos"]
h = ["hora", "horas"]
d = ["día", "días"]

[extend.aliases]
kilogram = ["kilo", "kilos"]